### ISSUE TITLE
tools for hmi

### ISSUE THREAD

**Issue by ltphong2605** [happydreamman/happydreamman#1]

**Comment by happydreamman** [comment]
https://github.com/happydreamman/FE2070/releases/tag/v1.0

**Comment by ltphong2605** [comment]
Thanks

**Comment by ltphong2605** [comment]
"FStudio version2.8" include FE3070, FE4070, FE5070, FE6070 and so on.
But it doesn't include only FE2070.
Please send me lower version of FStudio .
